---
apiVersion: v1
kind: ReplicationController
metadata:
  name: k8sapp
spec:
  replicas: 3
  selector:
    app: k8sapp
  template:
    metadata:
      labels:
        app: k8sapp
    spec:
      containers:
      - name: k8sapp
        image: nnbaocuong99/k8sapp
...
