apiVersion: v1
kind: Pod
metadata:
  name: k8sapp-gpu
spec:
  nodeSelector:
    # There is the typo in the book, "true" value should be in the quotes
    # so the fixed version is gpu: "True" instead of gpu: true
    gpu: "true"
  containers:
  - image: nnbaocuong99/k8sapp
    name: k8sapp
